// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABsRz-TkML54nU3aAj3ii40ZBKgi6sqX8',
    appId: '1:8333225477:web:ff58243a1e0069b413b66c',
    messagingSenderId: '8333225477',
    projectId: 'baseveterinaria',
    authDomain: 'baseveterinaria.firebaseapp.com',
    storageBucket: 'baseveterinaria.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrdphpRnNc96_i5_tXW7S2bLTgOHdLXYE',
    appId: '1:8333225477:android:3ca9fbb09a6f972e13b66c',
    messagingSenderId: '8333225477',
    projectId: 'baseveterinaria',
    storageBucket: 'baseveterinaria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2vOs5o8qB3AP-WbAoBwS2NnPKtozIgM',
    appId: '1:8333225477:ios:e0d6a4bd1023471513b66c',
    messagingSenderId: '8333225477',
    projectId: 'baseveterinaria',
    storageBucket: 'baseveterinaria.firebasestorage.app',
    iosBundleId: 'com.example.veterinariaMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA2vOs5o8qB3AP-WbAoBwS2NnPKtozIgM',
    appId: '1:8333225477:ios:e0d6a4bd1023471513b66c',
    messagingSenderId: '8333225477',
    projectId: 'baseveterinaria',
    storageBucket: 'baseveterinaria.firebasestorage.app',
    iosBundleId: 'com.example.veterinariaMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABsRz-TkML54nU3aAj3ii40ZBKgi6sqX8',
    appId: '1:8333225477:web:640c81bad346aa6713b66c',
    messagingSenderId: '8333225477',
    projectId: 'baseveterinaria',
    authDomain: 'baseveterinaria.firebaseapp.com',
    storageBucket: 'baseveterinaria.firebasestorage.app',
  );
}
